### ISSUE TITLE
New items only sporadically appear on homepage featured carousel

### ISSUE THREAD

**Issue by PeterArbaugh** [onflow/kitty-items#174]
When minting a new kitty item, the new item only sporadically appears on the featured homepage carousel.  Expectation is that a new item always appears as the first item on the carousel.

- Observed on testnet
- I was unable to reproduce in testing 1/7

**Comment by alse** [comment]
I wasn't able to reproduce this on a dev and a fresh testnet install. The homepage fetches listings from the database, so it's possible there was a discrepancy between the database and the testnet. This could have been caused by an error in the event listener or deletion of records from the database.

It would be great to add some error reporting to the app!

**Comment by drenz** [comment]
Can't reproduce
