### ISSUE TITLE
JS/Web apps port conflict - auth broken

### ISSUE THREAD

**Issue by benpolinsky** [onflow/kitty-items#36]
Hi There,

Thanks for the vast collection of learning resources and tutorials on Flow. Making my way though.

It seems that the node backend and the react web app are started on the same port. The web app runs fine on 3001, but Dapper staging auth is broken because of it.

I've been able authenticate and purchase an item by starting the node backend on 3001 and the web on 3000, but eventually ran into a CORS issue trying to list the same item. Perhaps that is a different issue, not sure.

Thanks

**Comment by 10thfloor** [comment]
Thanks for reporting @benpolinsky We've got a fix for this and a bunch of other stuff coming soon!

**Comment by Johnrobmiller** [comment]
I noticed that in env.local, the REACT_APP_PORT was already set to 3001.  I found a decent solution by modifying the package.json file so that "npm run start" launches the app at port 3001.  Here is the Stack Overflow I used that contains the code for Windows, Mac, and Linux: https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project

**Comment by 10thfloor** [comment]
This should be fixed when we merge PR #27

**Comment by 10thfloor** [comment]
Fixed by #27
